config/routes.rb
GuidedTrips::Application.routes.draw do

  # --- global configurations
  match 'config/:action' => 'configurations', :via => :put, :as => 'config'

  resources :pictures, :only => [:create, :show, :destroy] do 
    member do 
      put :use_as_index      
    end
  end

  resources :videos

  resources :trips do
    
    resources :comments, :only => [:index]

    collection do
      get :search
    end

    member do 
      post :handle_tag
      delete :handle_tag      
    end
  end
  match 'my_trips' => 'trips#my_trips', :as => 'my_trips'
  
  resources :activities
  resources :agencies, :only => [:show]
  resources :comments

  devise_for :users, :controllers => { 
    :registrations => "registrations", 
    :passwords => 'passwords',
    :omniauth_callbacks => "omniauth_callbacks"}
  devise_scope :user do
    get 'modal_sign_in' => 'sessions#new_as_modal'
  end  

  get "static/index"

  # --- Users
  match 'user/avatar' => 'user#update_avatar', :via => :post
  match 'users/edit' => 'users#edit', :as => 'user_root'
  resource :user do    
    resources :comments, :only => [:index], :controller => 'user/comments'
    resources :pictures, :only => [:index], :controller => 'user/pictures'
  end  

  match 'locations/:country' => 'locations#show', :as => 'locations_by_country'

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.  
  root :to => "static#index2"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/trip.rb
# == Schema Information
#
# Table name: trips
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  description      :text
#  location_id      :integer
#  included         :text
#  required         :text
#  price            :float
#  min_participants :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :integer
#  excerpt          :text
#  is_published     :boolean          default(FALSE)
#

class Trip < ActiveRecord::Base

  include CurrencyExchange
  extend FriendlyId
  friendly_id :name, use: :slugged

  attr_accessible :description, :included, :location_id, :min_participants, :name, :price, :required, :tag_list, :excerpt, :currency, :is_published
  attr_accessor :currency

  belongs_to :user
  belongs_to :location
  has_one :country, :through => :location
  has_one :agency, :through => :user
  has_many :activities, :dependent => :destroy
  has_many :pictures, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :videos, :dependent => :destroy

  validates :description, :name, :price, :presence => true
  validates :excerpt, length: { maximum: 200 }

  # by country
  scope :by_country, (lambda do |country|
    joins( :location ).where( 'locations.country' => country )
  end)  
  scope :published, where(:is_published => true)

  acts_as_taggable

  before_save :convert_currency


  # -------------------------------
  # => Search related stuff
  # -------------------------------

  # Solr - Searchable
  searchable :if => :is_published do
    autosuggest :trip_country, :using => :country_name

    latlon(:location) { Sunspot::Util::Coordinates.new(self.location.latitude, self.location.longitude) }

    text :description, :name
    text :location do 
      location.accent_city
    end
    text :country do 
      self.country_name
    end

    string :tag_list, :multiple => true do
      tag_list.map { |t| t}
    end

    integer :location_id

    integer :days do
      self.days
    end

    double :price do
      self.price.to_i
    end       
  end


  # get al activities of a day
  def activities_for_day( day=1 )
  	self.activities.where( :day => day )
  end

  # get number of days
  def days
  	d = self.activities.select( 'DISTINCT day' ).count
    d == 0 ? 1 : d
  end 

  # --- return the long version of the country
  def country_name
    self.country.name
  end

  def country
    self.location.country
  end

  # --- returns the image to use for index
  def picture_for_index
    self.pictures.use_for_index.first || self.pictures.first
  end

  # --- get average user rating
  def average_rating
    votings = self.comments.avg_voting.first
    {:sum => votings.sum, :vote => votings.avg_vote}
  end

  # --- is the passed user the editor?
  def is_the_editor? user
    self.user_id == user.id
  end

  # ---------------------------------
  #   Tag-Clouds
  # ---------------------------------

  # --- Country Cloud / Sum of trips per country
  def self.country_cloud( limit=10 )
    select( 'COUNT(*) AS sum, countries.name, locations.id AS id' ).joins( [:location, :country] ).group( 'countries.name' ).order( 'sum DESC' ).limit( limit )
  end

  # --- Tag Cloud
  # TODO: this belongs to ActsAsTaggableOn
  def self.tag_cloud( records )
    if records.any?
      rec_ids = records.collect {|rec| rec.id}

      ActsAsTaggableOn::Tag
        .select( "name, COUNT(*) AS 'sum'" )
        .where( "taggable_type = 'Trip' AND taggable_id IN (#{rec_ids.join(',')})" )
        .joins( :taggings ).group( :tag_id ).order( 'sum DESC' ) 
    else
      []
    end
  end  
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  
  before_filter :authenticate_user!, :only => [:my_trips, :new, :edit, :create, :update, :destroy]
  layout nil, :only => :search  

  # GET /trips
  def index
    get_results
    @search_mode = params['search-mode'] || 'location'
  end

  # Ajax, GET /trips  
  def search
    get_results    
    render :partial => 'list'
  end

  # --- list my trips as Agency
  def my_trips
    @trips = current_user.trips
  end


  # GET /trips/1
  def show
    @trip = Trip.find(params[:id])
  end

  # GET /trips/new
  def new
    @trip = Trip.new :user_id => current_user.id
  end

  # GET /trips/1/edit
  def edit
    @trip = current_user.trips.find(params[:id])
    @my_tags = @trip.tags.collect{|tag| tag.name }
  end

  # POST /trips
  def create
    @trip = Trip.new(params[:trip])
    @trip.user_id = current_user.id

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = current_user.trips.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = current_user.trips.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end

  # POST /trips/1/add_tag?tag=<tag_name>
  # DELETE /trips/1/remove_tag?tag=<tag_name>
  def handle_tag
    get_trip
    
    if request.post?
      @trip.tag_list.add( params[:tag] )
    elsif request.delete?
      @trip.tag_list.remove( params[:tag] )
    end
    @trip.save!    
    render json: {:success => true}.to_json
  end

  private 

  def get_trip
    @trip = current_user.trips.find( params[:id] ) 
  end

  # --- General Trip Search
  def get_results

    days_count = params[:days].to_i
    @location = Location.find(params[:location_id]) if params[:location_id]

    # fulltext search
    if params[:search] or params[:location_id]
      search = Trip.search do

        # fulltext or location based search
        if @location.present?
          max_km = 100
          with(:location).in_radius(@location.latitude, @location.longitude, max_km, :bbox => true)
        elsif params[:search].present?
          fulltext params[:search] do
            query_phrase_slop 1
          end
        end

        with(:tag_list).any_of(params[:tags].split(',')) if params[:tags].present?

        # how many days?
        if [1,2,3].include? days_count
          with(:days, days_count)
        elsif days_count == 4
          with(:days).less_than(7)
        elsif days_count == 5
          with(:days).greater_than(6)
        end

        # maximum price
        with(:price).less_than(params[:price].to_i) if params[:price].present?
      end
      @trips = search.results
    end

    @trips ||= Trip.published.all
  end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_edit_tags.html.haml
- if @my_tags
  .margin-bottom-40
    .headline
      %h3= t('edit_tags.title')
    - t('tags').each do |tag_name|
      = link_to tag_name, handle_tag_trip_path( @trip, :tag => tag_name ), :class => "label handle_tag label-#{@my_tags.include?( tag_name ) ? 'success' : 'default'}" 

app/views/trips/_list.html.haml
/ List Trip Results
.trips-result
  
  / Trip-Tags
  #trip_tags
    - Trip.tag_cloud( @trips ).each do |tag|
      %span.label.label-info= tag.name
  
  = render :partial => 'trip', :collection => @trips

app/views/trips/_search_bar.html.haml
.row
  = form_tag(trips_path, :method => :get, :class => "form-inline", :id => 'trips_search') do 
    
    // submit location-ID here
    = hidden_field_tag :location_id, params[:location_id]
    .input-group.col-lg-5
      .input-group-btn
        .btn.btn-default.dropdown-toggle{'data-toggle' => 'dropdown'} 
          %span.search-mode
          %span.caret
        %ul.dropdown-menu{:id => 'search_mode_select'}
          %li= link_to(t('trips.search.mode.location'), '#')
          %li= link_to(t('trips.search.mode.text'), '#')
      = text_field_tag :search, params[:search], :class => 'search-term form-control', :id => 'prededDropdownButton'

    .form-group.col-lg-2
      = select_tag :days, options_for_select( t('trips.search.days').each_with_index.collect{|d, i| [d, i]}), :class => 'form-control styled-select'

    .input-group.col-lg-3
      %span.input-group-addon= icon_label 'Max', users_currency.downcase
      = text_field_tag :price, '', :id => 'appendedPrependedInput', :class => 'form-control'

    .form-group.col-lg-2
      = button_tag icon_label(t('button.search'), 'search'), :class => 'btn btn-primary'

- content_for :doc_footer do
  :javascript
    $(document).ready(function() {
      TripsSearch.init( '#trips_search', '#trips_result', '#trip_tags_checkboxes', '#{t("trip.search.mode.#{@search_mode}")}' );
    });

app/views/trips/_tag_cloud.html.haml
/ Tags Filter for Trips-Result
-#
	%ul.nav.nav-list
		- Trip.tag_cloud( trips ).each do |tag|
			%li= label_tag( nil, "#{check_box_tag(:tag, tag_name, false)} #{tag_name}".html_safe, :class => 'checkbox' )

#trip_tags
	- t('tags').each do |tag_name|
		%span.label.label-default= icon_label tag_name, 'check-empty'

app/views/trips/_trip.html.haml
= content_tag :div, class: 'trip-preview-container trip', data: {lon: trip.location.longitude, lat: trip.location.latitude}, style: "background-color: #FAFAFA; margin-bottom: 20px;" do
  .blog.blog-medium
    .row  
      .col-md-3.trip-image
        = image_tag( trip.picture_for_index.file.url(:thumb), class: 'img-responsive' ) if trip.picture_for_index
      
      .col-md-9
        .clearfix
          %h2.pull-left= link_to trip.name, trip
          .pull-right.trip-price= number_to_multi_currency( trip.convert_price_to( users_currency ), users_currency.downcase, :precision => 0 )

        .trip-excerpt
          .row
            .col-md-8      
              - if trip.comments.any?
                %ul.list-unstyled.list-inline.blog-info
                  %li= star_rating_outp trip.average_rating[:vote].to_i
                  %li= icon_label t('trips.comment_count', count: trip.average_rating[:sum]), 'comments'        

              %p= trip.excerpt
              %p= icon_link_to t('trips.preview.button_label'), trip, 'chevron-right', class: 'btn-u btn-u-small'

            .col-md-4
              %ul.list-unstyled.list-inline.blog-info.who
                %li= icon_label "#{trip.location.country_name}, #{trip.location.accent_city}", 'globe'
                %li= icon_label t('trips.preview.days', :count => trip.days).html_safe, 'calendar'
                %li.trip-tags= trip.tags.collect.each{|tag| content_tag(:span, tag.name, class: 'label label-default')}.join(' ').html_safe

app/views/trips/_trip_small.html.haml
= content_tag :div, class: 'trip-small-preview-container' do
  .row  
    .col-md-2.trip-image
      = image_tag( trip.picture_for_index.file.url(:fixed_thumb), :class => 'img-responsive' ) if trip.picture_for_index
    
    .col-md-10
      .clearfix
        %h4.pull-left= link_to trip.name, trip
        .pull-right.trip-price= number_to_currency( trip.price, :precision => 0 )

      %ul.list-unstyled.list-inline.trip-tag-line
        %li= icon_label "#{trip.location.country_name}, #{trip.location.accent_city}", 'globe'
        %li= icon_label t('trips.preview.days', :count => trip.days).html_safe, 'calendar'
        
        - if trip.comments.any?
          %li.pull-right
            %ul.list-unstyled.list-inline
              %li= star_rating_outp trip.average_rating[:vote].to_i             

app/views/trips/edit.html.haml
= breadcrumps t('trips.buttons.edit'), [link_to('home', root_path), link_to('My trips', my_trips_path)]

.container

  - unless @trip.is_published?
    .alert.alert-warning= t('trips.show.unpublished_notice')

  .row
    .col-md-7
      
      .tab-v2
        %ul.nav.nav-tabs
          %li.active= link_to t('.tabs.details'), '#details', data: {toggle: 'tab'}
          %li= link_to t('.tabs.pictures'), '#pictures', data: {toggle: 'tab'}
          %li= link_to t('.tabs.videos'), '#videos', data: {toggle: 'tab'}
        
        .tab-content

          // --- Form Tab
          #details.tab-pane.active
            = simple_form_for @trip do |f|
              = f.hidden_field :location_id, :id => 'location_id'

              = show_errors( @trip ) if @trip.errors.any?
              
              = f.input :is_published
              
              .form-group
                = f.label :location
                = text_field_tag :location, (@trip.location.autocomplete_string if @trip.location.present?), 
                  :class => 'autosuggest-location tooltip-field form-control', :data => {:content => t('trips.tooltips.location')}

              = f.input :name, :input_html => {:class => 'tooltip-field', :data => {:content => t('trips.tooltips.name')}}
              = f.input :description, :input_html => {:rows => 12, :class => 'tooltip-field wysihtml5', :data => {:content => t('trips.tooltips.description')}}
              = f.input :excerpt, :input_html => {:rows => 3, :class => 'tooltip-field', :data => {:content => t('trips.tooltips.excerpt')}}
              = f.input :included, :input_html => {:rows => 4, :class => 'tooltip-field', :data => {:content => t('trips.tooltips.included')}}
              = f.input :required, :input_html => {:rows => 4, :class => 'tooltip-field', :data => {:content => t('trips.tooltips.required')}}
              
              .form-group
                = f.label :price
                .input-group
                  .input-group-btn
                    = f.select :currency, AppConfig.major_currencies, { selected: users_currency }, 
                    {:class => 'form-control', :style => 'width:80px; border-right: none'}
                  = f.text_field :price, :value => @trip.convert_price_to( users_currency ), :class => 'tooltip-field form-control', :data => {:content => t('trips.tooltips.price')}

              = f.input :min_participants, :input_html => {:class => 'tooltip-field', :data => {:content => t('trips.tooltips.min_participants')}}

              .control-group
                .controls= f.submit t('button.save'), :class => 'btn btn-primary'

          // --- Pictures Tab
          #pictures.tab-pane
            = render 'pictures/new'

          // --- Videos Tab
          #videos.tab-pane
            = render 'videos/new'
    .col-md-5
      = render 'edit_tags' unless @trip.new_record?
      = render 'activities/menu', :trip => @trip

  %hr
  = icon_link_to t('trips.buttons.show'), @trip, 'pencil', :class => 'btn'
  = icon_link_to t('trips.buttons.list'), trips_path, 'arrow-left', :class => 'btn'

app/views/trips/index.html.haml
= breadcrumps link_to(t('trips.title'), trips_path), [link_to('home', root_path)]

.container

  .row.blog-page

    // --- Main Container
    .col-md-9
      = render 'search_bar'

      #trips_result
        - if @trips.any?
          = render 'list'
        - else
          .alert.alert-warning{style: "margin-top:20px;"}
            = t('trips.search.no_results')
          
          - if @location.present?
            = content_tag :div, '', class: 'trip', data: {lon: @location.longitude, lat: @location.latitude}


    // --- Sidebar
    .col-md-3
      .gmap4.well{:style => 'height: 300px; width: 100%'}
      = render 'tag_cloud', :trips => @trips
 

app/views/trips/my_trips.html.haml
= breadcrumps 'My guided trips', [link_to('home', root_path)]

.container.my-trips
  .row
    .col-md-9

      - if @trips.empty?
        .alert.alert-info= t('.no_current_trips')

      - else    
        %table.table-striped{style: "width:80%"}
          %thead
            %tr
              %th Name
              %th Updated
              %th

          %tbody
            - @trips.each do |trip|
              %tr
                %th.trip-name= link_to trip.name, trip
                %td= l(trip.created_at, :format => :short_date)
                %td.cf
                  .btn-group.pull-right
                    %button{:class => "btn dropdown-toggle", :'data-toggle' => "dropdown"}
                      Action 
                      %span.caret

                    %ul.dropdown-menu
                      %li= icon_link_to 'Show', trip, 'eye-open'
                      %li= icon_link_to 'Edit', edit_trip_path(trip), 'pencil'
                      %li= icon_link_to 'Destroy', trip, 'trash', :method => :delete, :data => { :confirm => t('general.confirm_delete') }
    .col-md-3
      = link_to icon_label(t('trips.new_trip'), 'plus'), new_trip_path, :class => 'btn btn-primary'

app/views/trips/new.html.haml
= breadcrumps 'New trip', [link_to('home', root_path), link_to('My trips', my_trips_path)]

.container
  = simple_form_for @trip do |f|
    = f.hidden_field :location_id, :id => 'location_id', :class => 'autosuggest-location-id'
    = show_errors( @trip ) if @trip.errors.any?

    .row
      .col-md-6
        .form-group
          = f.label :location
          = text_field_tag :location, (@trip.location.autocomplete_string if @trip.location.present?), 
            :class => 'autosuggest-location tooltip-field form-control', :data => {:content => t('trips.tooltips.location')}

        = f.input :name, :input_html => {:class => 'tooltip-field', :data => {:content => t('trips.tooltips.name')}}
        = f.input :description, :input_html => { :rows => 6, :class => 'tooltip-field wysihtml5', :data => {:content => t('trips.tooltips.description') }}
        = f.input :included, :input_html => { :rows => 4, :class => 'tooltip-field', :data => {:content => t('trips.tooltips.included') }}
        = f.input :required, :input_html => { :rows => 4, :class => 'tooltip-field', :data => {:content => t('trips.tooltips.required') }}
        
        .form-group
          = f.label :price
          .input-group
            %span.input-group-addon= icon_label '', 'usd'
            = f.text_field :price, :id => "appendedPrependedInput", :class => 'tooltip-field form-control', :data => {:content => t('trips.tooltips.price')}
        = f.input :min_participants, :class => 'tooltip-field', :data => {:content => t('trips.tooltips.min_participants')}

        .control-group
          .controls= f.submit t('button.save'), :class => 'btn btn-primary'

app/views/trips/show.html.haml
= breadcrumps @trip.name, [link_to('home', root_path), link_to('trips', trips_path)]

#trips_detail.container

  - unless @trip.is_published?
    .alert.alert-warning= t('.unpublished_notice')

  // ---- Main - Container
  .row.blog-page
    .col-md-8

      .blog.margin-bottom-40

        %h2= t('.agency_link_html', :agency_name => link_to(@trip.agency.name, @trip.agency, class: 'color-blue'))
        .blog-post-tags
          %ul.list-unstyled.list-inline.blog-info
            - if @trip.comments.any?
              %li= star_rating_outp @trip.average_rating[:vote].to_i
              %li= icon_label t('trips.user_vote_html', vote: @trip.average_rating[:vote]), 'smile'
              %li= icon_label t('trips.comment_count', count: @trip.average_rating[:sum]), 'comments'

          - if @trip.tag_list.any?
            %ul.list-unstyled.list-inline.blog-tags
              %li
                - @trip.tag_list.each do |tag|
                  = link_to tag.capitalize, '#'

        / description
        .margin-bottom-40
          %h3= t('activerecord.attributes.trip.description')
          %p= @trip.description.html_safe
        
        - if @trip.included.present?
          .margin-bottom-40
            %h3= t('activerecord.attributes.trip.included')
            %p= @trip.included
        
        - if @trip.required.present?
          .margin-bottom-40
            %h3= t('activerecord.attributes.trip.required')
            %p= @trip.required

      / Tabs
      .tab-v2.margin-bottom-40
        %ul.nav.nav-tabs
          %li.active= link_to t('.tabs.professional_photos'), '#professional_photos', data: {toggle: 'tab'}
          %li= link_to t('.tabs.traveler_photos'), '#traveler_pictures', data: {toggle: 'tab'}
          %li= link_to t('.tabs.videos'), '#videos', data: {toggle: 'tab'}
        
        .tab-content
          #professional_photos.tab-pane.active
            - if user_signed_in? and current_user.is_agency?
              = link_to t('picture.new.agency_upload'), edit_trip_path( @trip, anchor: 'pictures' ), class: 'btn btn-primary'

            - if @trip.pictures.from_agency.any?
              .flexslider            
                %ul.slides.carousel              
                  - @trip.pictures.from_agency.each_with_index do |pic, index|
                    %li
                      = link_to( pic.file.url(:big), data: {rel: 'fancybox-button'}, class: 'fancybox-button zoomer') do
                        %span.overlay-zoom
                          = image_tag( pic.file.url(:fixed_thumb))
                          .zoom-icon

          #traveler_pictures.tab-pane
            .gallery-container.clearfix
              = render partial: "pictures/picture", collection: @trip.pictures.from_traveler
            
            - if user_signed_in?
              - unless current_user.is_agency?
                = form_for Picture.new(:trip_id => @trip.id), :html => { :multipart => true } do |f|
                  = f.hidden_field :trip_id
                  = f.file_field :file, class: 'file btn-primary', title: t('picture.new.browse')
                  = f.submit t('button.upload'), :class => 'btn btn-primary'
            - else
              .alert.alert-info= t('picture.new.login_before')
      
          #videos.tab-pane
            .video-container
              - @trip.videos.each do |video|
                .row.blog.blog-medium.margin-bottom-30
                  .col-md-3.img-container
                    = link_to( video, title: t('picture.zoom'), class: "zoomer remote-modal") do
                      %span.overlay-zoom
                        = image_tag( video.thumbnail, style: "width:100%" )
                        .zoom-icon
                  .col-md-9
                    %h4= video.title
                    %p= truncate video.description, length: 280

      / Comments
      #comments_tab
        .headline
          %h2= t('.comments_title')
        - if @trip.comments.empty?
          %p= t('comments.no_comments')
        - else
          = comments_for( @trip )
        - if user_signed_in? and !current_user.is_agency?
          = icon_link_to t('trips.add_comment'), new_comment_path( :trip_id => @trip.id ), 'comment', :class => "btn-u btn-u-blue remote-modal"    

      - if user_signed_in? and @trip.is_the_editor? current_user
        %hr
        = icon_link_to t('button.edit'), edit_trip_path(@trip), 'pencil', :class => 'btn-u'
        = icon_link_to t('trips.buttons.list'), trips_path, 'arrow-left', :class => 'btn-u'

        - if @trip.is_published?
          = link_to t('trips.buttons.unpublish'), trip_path(@trip, {:trip => {:is_published => false}}), :class => 'btn-u btn-u-red', :method => 'put'
        - else
          = link_to t('trips.buttons.publish'), trip_path(@trip, {:trip => {:is_published => true}}), :class => 'btn-u btn-u-green', :method => 'put'


    // ---- Side-Bar Container
    .col-md-4.magazine-page
      
      / Google Mpas
      .headline.headline-md
        %h2= t('.location_title')
      .well.margin-bottom-40{:style => 'padding: 0; text-align: center'}
        = draw_a_map( @trip.location )

      .headline.headline-md
        %h2= t('.facts_title')
      %table.table.table-bordered.margin-bottom-40
        %tr
          %th= t('activerecord.attributes.trip.price')
          %td= number_to_multi_currency( @trip.convert_price_to( users_currency ), users_currency.downcase, :precision => 0 )  
        %tr
          %th= t('activerecord.attributes.trip.min_participants')
          %td= @trip.min_participants
        %tr
          %th= t('activerecord.attributes.trip.days')
          %td= @trip.days  
      
      - if user_signed_in? and current_user.is_agency?
        = render 'activities/menu', :trip => @trip
      - else
        .headline.headline-md
          %h2= t('.activities_title')
        = render 'activities/list', :trip => @trip