config/routes.rb
GuidedTrips::Application.routes.draw do

  # --- global configurations
  match 'config/:action' => 'configurations', :via => :put, :as => 'config'

  resources :pictures, :only => [:create, :show, :destroy] do 
    member do 
      put :use_as_index      
    end
  end

  resources :videos

  resources :trips do
    
    resources :comments, :only => [:index]

    collection do
      get :search
    end

    member do 
      post :handle_tag
      delete :handle_tag      
    end
  end
  match 'my_trips' => 'trips#my_trips', :as => 'my_trips'
  
  resources :activities
  resources :agencies, :only => [:show]
  resources :comments

  devise_for :users, :controllers => { 
    :registrations => "registrations", 
    :passwords => 'passwords',
    :omniauth_callbacks => "omniauth_callbacks"}
  devise_scope :user do
    get 'modal_sign_in' => 'sessions#new_as_modal'
  end  

  get "static/index"

  # --- Users
  match 'user/avatar' => 'user#update_avatar', :via => :post
  match 'users/edit' => 'users#edit', :as => 'user_root'
  resource :user do    
    resources :comments, :only => [:index], :controller => 'user/comments'
    resources :pictures, :only => [:index], :controller => 'user/pictures'
  end  

  match 'locations/:country' => 'locations#show', :as => 'locations_by_country'

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.  
  root :to => "static#index2"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id                :integer          not null, primary key
#  trip_id           :integer
#  user_id           :integer
#  agency_image      :boolean
#  file_file_name    :string(255)
#  file_content_type :string(255)
#  file_file_size    :integer
#  file_updated_at   :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  use_for_index     :boolean
#

class Picture < ActiveRecord::Base
  attr_accessible :agency_image, :trip_id, :user_id, :file, :use_for_index

  before_save :check_single_index_use

  has_attached_file :file, 
    :styles => { :big => "600x400>", :medium => "300x200>", :thumb => "300x260#", :fixed_thumb => "160x120#", :sx => "100x80>" }

  belongs_to :trip
  belongs_to :user

  validates :file, :presence => true

  scope :use_for_index, :conditions => {:use_for_index => true, :agency_image => true}
  scope :from_agency, where(:agency_image => true)
  scope :from_traveler, where(:agency_image => false)


  # --- makes sure that only one Agency image is used for index
  def check_single_index_use
    if self.agency_image and self.use_for_index
      if former_index_pic = Picture.use_for_index.where( :trip_id => self.trip_id ).first
        former_index_pic.update_attribute( :use_for_index, false )
      end
    end
  end
  
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  before_filter :authenticate_user!, :except => [:show]
  layout 'modal', :only => [:show]


  # --- show picture in fullsize mode
  # currently not used
  def show
  #  @zoom_pic = Picture.find params[:id]
  #  @all_pictures = Picture.where( :trip_id => @zoom_pic.trip_id )
  end

  # --- Upload a Picture
  def create

    @pic = Picture.new( params[:picture] )
    @pic.user_id = current_user.id
    @pic.agency_image = current_user.is_agency?  

    if @pic.save
      flash[:notice] = t('general.successfully_saved')
    else
      flash[:error] = @pic.errors.full_messages.join(', ')
    end
    goto
  end

  # --- delete a picture (if you have the right to do so)
  def destroy
    @pic = current_user.pictures.find( params[:id] )
    if @pic.delete
      flash[:notice] = t('general.successfully_destroyed')
    else
      flash[:error] = t('general.no_rights')
    end      
    goto
  end

  # --- set this picture as preview
  def use_as_index
    @pic = current_user.pictures.find( params[:id] )
    @pic.update_attribute(:use_for_index, true)
    goto
  end

  private 

  # --- return to where you come from
  def goto
    if current_user.is_agency?
      redirect_to edit_trip_path( @pic.trip, :anchor => 'pictures' )
    else  
      redirect_to @pic.trip
    end
  end
end

app/controllers/user/pictures_controller.rb
class User::PicturesController < ApplicationController

  before_filter :authenticate_user!

  # --- list
  # GET /users/:id/comments
  def index
    @grouped_pictures = current_user.pictures.group_by {|p| p.trip}
  end

end

app/views/pictures/_new.html.haml
- if user_signed_in?
  = form_for Picture.new(:trip_id => @trip.id), :html => { :multipart => true } do |f|
    = f.hidden_field :trip_id
    = f.file_field :file, class: 'file btn-primary', title: t('picture.new.browse')
    = f.submit t('button.upload'), :class => 'btn btn-primary'
  %hr

.gallery-container.clearfix
  - @trip.pictures.each do |pic|
    = content_tag :div, class: "img-container#{' index-pic' if pic.use_for_index}" do
      = link_to( pic.file.url(:big), data: {rel: 'fancybox-button'}, title: t('picture.zoom'), class: "fancybox-button zoomer") do
        %span.overlay-zoom
          = image_tag( pic.file.url(:fixed_thumb))
          .zoom-icon
      .actions.clearfix
        = icon_link_to '', pic, 'trash', {:method => :delete, :title => t('button.delete')}
        = icon_link_to '', use_as_index_picture_path( pic ), 'asterisk', {:method => :put, :title => t('picture.use_for_index')} unless pic.use_for_index

app/views/pictures/_pager.html.haml
#pictures_tab
  %ul.bxslider
    - @trip.pictures.each do |pic|
      %li.center= image_tag( pic.file.url(:big))    

  #picture_pager
    - @trip.pictures.each_with_index do |pic, index|
      = image_tag pic.file.url(:thumb), :data => {'slide-index' => index}, :class => 'img-polaroid'

app/views/pictures/_picture.html.haml
= content_tag :div, class: "img-container" do
  = link_to( picture.file.url(:big), data: {rel: 'fancybox-button'}, title: t('picture.zoom'), class: "fancybox-button zoomer") do
    %span.overlay-zoom
      = image_tag( picture.file.url(:fixed_thumb))
      .zoom-icon

app/views/pictures/show.html.haml
- content_for :modal_header do
  Gallery

- content_for :modal_body do
  #zoom_gallery{:style => "width: 810px;"}
    .zoom-image= image_tag( @zoom_pic.file.url(:big), :class => 'img-polaroid')

    - @all_pictures.each do |pic|
      .img-container.img-polaroid= image_tag pic.file.url(:thumb)

  = javascript_tag 'init_pictures();'