config/routes.rb
GuidedTrips::Application.routes.draw do

  # --- global configurations
  match 'config/:action' => 'configurations', :via => :put, :as => 'config'

  resources :pictures, :only => [:create, :show, :destroy] do 
    member do 
      put :use_as_index      
    end
  end

  resources :videos

  resources :trips do
    
    resources :comments, :only => [:index]

    collection do
      get :search
    end

    member do 
      post :handle_tag
      delete :handle_tag      
    end
  end
  match 'my_trips' => 'trips#my_trips', :as => 'my_trips'
  
  resources :activities
  resources :agencies, :only => [:show]
  resources :comments

  devise_for :users, :controllers => { 
    :registrations => "registrations", 
    :passwords => 'passwords',
    :omniauth_callbacks => "omniauth_callbacks"}
  devise_scope :user do
    get 'modal_sign_in' => 'sessions#new_as_modal'
  end  

  get "static/index"

  # --- Users
  match 'user/avatar' => 'user#update_avatar', :via => :post
  match 'users/edit' => 'users#edit', :as => 'user_root'
  resource :user do    
    resources :comments, :only => [:index], :controller => 'user/comments'
    resources :pictures, :only => [:index], :controller => 'user/pictures'
  end  

  match 'locations/:country' => 'locations#show', :as => 'locations_by_country'

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.  
  root :to => "static#index2"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id          :integer          not null, primary key
#  trip_id     :integer
#  day         :integer
#  time        :time
#  text        :text
#  location_id :integer
#

class Activity < ActiveRecord::Base
  attr_accessible :day, :location_id, :text, :time, :trip_id, :hour, :minute
  attr_accessor :hour, :minute

  validates :day, :text, :presence => true
  default_scope :order => 'activities.time ASC'
  belongs_to :trip

  # callbacks
  after_initialize :set_accessors
  before_save :transform_time


  private

  def set_accessors
    if self.time
      self.hour = self.time.hour
      self.minute = self.time.min
    end
  end

  def transform_time
    self.time = Time.parse("#{self.hour}:#{self.minute}") if self.hour.present? and self.minute.present?
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

	layout 'modal', :except => [:create, :destroy]

  # --- edit
  def edit
    get_activity
  end

  def update
    get_activity
    if @activity.update_attributes( params[:activity] )
      resp = {:success => true, :msg => t('general.successfully_updated'), :redirect_to => "/trips/#{@trip.id}"}
    else
      resp = {:success => false, :msg => @activity.errors.full_messages.join(', ')}
    end

    respond_to do |format|
      format.json { render json: resp.to_json }
    end
  end


  # --- new
  def new
  	@activity = Activity.new
    trip = Trip.find( params[:trip_id] )
    @activity.day = params[:day]
    @activity.trip_id = trip.id
  end

  def create
    activity = Activity.new params[:activity]    
    
    if activity.save
      resp = {:success => true, :msg => t('general.successfully_saved'), :redirect_to => "/trips/#{activity.trip_id}"}
    else
      resp = {:success => false, :msg => activity.errors.full_messages.join(', ')}
    end

    respond_to do |format|
      format.json { render json: resp.to_json }
    end
  end

  # --- Destroy
  def destroy
    get_activity    
    flash[:notice] = t('general.successfully_destroyed') if @activity.destroy
    redirect_to @trip
  end

  private 

  def get_activity
    @activity = current_user.activities.find( params[:id] )
    @trip = @activity.trip
  end
end

app/views/activities/_list.html.haml
.blog-twitter
  - day = 0
  - trip.days.times do
    - day += 1

    %h3= t('trips.day_title', :day => day)
    - trip.activities_for_day( day ).each do |activity|
      .blog-twitter-inner
        .time= activity.time.strftime('%H:%M') 
        %span= activity.text

app/views/activities/_menu.html.haml
.headline
  %h3= t('activity.menu.title')

.activity-menu
  - day = 0
  - has_activites = false
  - trip.days.times do
    - day += 1
    %h4.nav-header= t('trips.day_title', :day => day)

    .margin-bottom-40
      - trip.activities_for_day( day ).each do |activity|
        - has_activites = true
        .activity-item
          .row
            .col-md-2.time= activity.time.strftime('%H:%M') 
            .col-md-10.text
              = activity.text
              %ul.fa-buttons.pull-right
                %li= icon_link_to '', edit_activity_path( activity ), 'edit', :class => "remote-modal", :title => t('button.edit')
                %li= icon_link_to '', activity, 'trash', :method => :delete, :confirm => t('general.confirm_delete'), :title => t('button.delete')
        
      = icon_link_to t('trips.add_activity'), new_activity_path( :day => day, :trip_id => trip.id ), 'plus-sign', :class => "remote-modal"

  - if has_activites
    %h4.nav-header= t('trips.day_title', :day => (day+1))
    = icon_link_to t('trips.add_activity'), new_activity_path( :day => (day+1), :trip_id => trip.id ), 'plus-sign', :class => "remote-modal"

app/views/activities/edit.html.haml
- content_for :modal_header do
  Edit Activity

- content_for :modal_body do  

  .flash_msg{:style => 'display: none'}

  = form_for @activity do |f|
    
    .row
      .col-md-6.form-group
        = f.label :hour
        = f.select :hour, options_for_select((1..24).to_a), {}, {:class => 'form-control'}
      .col-md-6.form-group
        = f.label :minute
        = f.select :minute, options_for_select([0,15,30,45]), {}, {:class => 'form-control'}
    
    .form-group
      = f.label :text
      = f.text_area :text, :rows => 4, :class => 'form-control'

- content_for :modal_footer do  
  = submit_tag t('button.save'), :class => 'btn btn-primary'

app/views/activities/new.html.haml
- content_for :modal_header do
	= t('activity.new.title')

- content_for :modal_body do	

	.flash_msg{:style => 'display: none'}

	= form_for @activity do |f|
		= f.hidden_field :trip_id
		= f.hidden_field :day

		.row
			.col-md-6.form-group
				= f.label :hour
				= f.select :hour, options_for_select((1..24).to_a), {}, {:class => 'form-control'}
			.col-md-6.form-group
				= f.label :minute
				= f.select :minute, options_for_select([0,15,30,45]), {}, {:class => 'form-control'}
		
		.form-group
			= f.label :text
			= f.text_area :text, :rows => 4, :class => 'form-control'

- content_for :modal_footer do	
	= submit_tag t('button.save'), :class => 'btn btn-primary'