config/routes.rb
GuidedTrips::Application.routes.draw do

  # --- global configurations
  match 'config/:action' => 'configurations', :via => :put, :as => 'config'

  resources :pictures, :only => [:create, :show, :destroy] do 
    member do 
      put :use_as_index      
    end
  end

  resources :videos

  resources :trips do
    
    resources :comments, :only => [:index]

    collection do
      get :search
    end

    member do 
      post :handle_tag
      delete :handle_tag      
    end
  end
  match 'my_trips' => 'trips#my_trips', :as => 'my_trips'
  
  resources :activities
  resources :agencies, :only => [:show]
  resources :comments

  devise_for :users, :controllers => { 
    :registrations => "registrations", 
    :passwords => 'passwords',
    :omniauth_callbacks => "omniauth_callbacks"}
  devise_scope :user do
    get 'modal_sign_in' => 'sessions#new_as_modal'
  end  

  get "static/index"

  # --- Users
  match 'user/avatar' => 'user#update_avatar', :via => :post
  match 'users/edit' => 'users#edit', :as => 'user_root'
  resource :user do    
    resources :comments, :only => [:index], :controller => 'user/comments'
    resources :pictures, :only => [:index], :controller => 'user/pictures'
  end  

  match 'locations/:country' => 'locations#show', :as => 'locations_by_country'

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.  
  root :to => "static#index2"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/_footer.html.haml
/ === Footer ===
.footer
  .container
    .row
      .col-md-4.md-margin-bottom-40
        / About
        .headline
          %h2 About
        %p.margin-bottom-25.md-margin-bottom-40 Unify is an incredibly beautiful responsive Bootstrap Template for corporate and creative professionals.
        / Monthly Newsletter
        .headline
          %h2 Monthly Newsletter
        %p Subscribe to our newsletter and stay up to date with the latest news and deals!
        %form.footer-subsribe
          .input-group
            %input.form-control{placeholder: "Email Address", type: "text"}/
            %span.input-group-btn
              %button.btn-u{type: "button"} Subscribe
          / /input-group
      / /col-md-4
      .col-md-4.md-margin-bottom-40
        .posts
          .headline
            %h2 Recent Blog Entries
          %dl.dl-horizontal
            %dt
              %a{href: "#"}
                %img{alt: "", src: "/images/elastislide/6.jpg"}/
            %dd
              %p
                %a{href: "#"} Anim moon officia Unify is an incredibly beautiful responsive Bootstrap Template
          %dl.dl-horizontal
            %dt
              %a{href: "#"}
                %img{alt: "", src: "/images/elastislide/10.jpg"}/
            %dd
              %p
                %a{href: "#"} Anim moon officia Unify is an incredibly beautiful responsive Bootstrap Template
          %dl.dl-horizontal
            %dt
              %a{href: "#"}
                %img{alt: "", src: "/images/elastislide/11.jpg"}/
            %dd
              %p
                %a{href: "#"} Anim moon officia Unify is an incredibly beautiful responsive Bootstrap Template
      / /col-md-4
      .col-md-4
        / Monthly Newsletter
        .headline
          %h2 Contact Us
        %address.md-margin-bottom-40
          25, Lorem Lis Street, Orange
          %br/
          California, US
          %br/
          Phone: 800 123 3456
          %br/
          Fax: 800 123 3456
          %br/
          Email:
          %a{href: "mailto:info@anybiz.com"} info@anybiz.com
        / Stay Connected
        .headline
          %h2 Stay Connected
        %ul.social-icons
          %li
            %a.social_rss{"data-original-title" => "Feed", href: "#"}
          %li
            %a.social_facebook{"data-original-title" => "Facebook", href: "#"}
          %li
            %a.social_twitter{"data-original-title" => "Twitter", href: "#"}
          %li
            %a.social_googleplus{"data-original-title" => "Goole Plus", href: "#"}
          %li
            %a.social_pintrest{"data-original-title" => "Pinterest", href: "#"}
          %li
            %a.social_linkedin{"data-original-title" => "Linkedin", href: "#"}
          %li
            %a.social_vimeo{"data-original-title" => "Vimeo", href: "#"}

/ === Copyright ===
.copyright
  .container
    .row
      .col-md-6
        %p.copyright-space
          2014 © GuidedTrip.com ALL Rights Reserved.
          %a{href: "#"} Privacy Policy
          |
          %a{href: "#"} Terms of Service
      .col-md-6
        %a{href: "index.html"}
          =# image_tag 'logo2-default.png', :id => "logo-footer", :class => "pull-right"

app/views/layouts/_login_bar.html.haml
.top
  .container
    %ul.loginbar.pull-right

      %li
        %i.icon-exchange
        %a Currencies
        %ul.currencies
          - AppConfig.major_currencies.each do |code|
            = content_tag :li, :class => (users_currency == code ? 'active' : '') do
              = icon_link_to( code, config_path(:set_currency, :currency => code), code.downcase, :method => 'put' )
          
      - if user_signed_in?
        %li.devider
        %li= link_to 'Logout', destroy_user_session_path, :method =>  'delete'
      -else
        %li.devider
        %li= link_to 'Sign up', new_registration_path(resource_name)
        %li.devider
        %li= link_to 'Login', '/modal_sign_in', :class => 'remote-modal'
        - #%li= link_to 'Login', new_session_path(resource_name)

app/views/layouts/_sample_navigation.html.haml
/ === Header ===
.header
  .navbar.navbar-default{role: "navigation"}
    .container
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand.style-icons{href: "/"}
          %i.icon-comments-alt.icon-round.icon-bg-grey{style: "text-align: center"}
          %span.logo guided-trips.com
          
      / Collect the nav links, forms, and other content for toggling
      .collapse.navbar-collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown.active
            %a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown", "data-toggle" => "dropdown", href: "#"}
              Home
              %i.icon-angle-down
            %ul.dropdown-menu
              %li.active
                %a{href: "index.html"} Option 1: Default Page
              %li
                %a{href: "page_home1.html"} Option 2: Layer Slider
              %li
                %a{href: "page_home2.html"} Option 3: Revolution Slider
              %li
                %a{href: "page_home3.html"} Option 4: Amazing Content
              %li
                %a{href: "page_home4.html"} Option 5: Home Sidebar
              %li
                %a{href: "page_home5.html"} Option 6: Home Flatty
              %li
                %a{href: "page_home6.html"} Option 7: Home Magazine
              %li
                %a{href: "page_home7.html"} Option 8: Home Portfolio
          %li.dropdown
            %a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown", "data-toggle" => "dropdown", href: "#"}
              Pages
              %i.icon-angle-down
            %ul.dropdown-menu
              %li
                %a{href: "page_about.html"} About Us
              %li
                %a{href: "page_about1.html"} About Us Option
              %li
                %a{href: "page_services.html"} Services
              %li
                %a{href: "page_services1.html"} Services Option
              %li
                %a{href: "page_pricing.html"} Pricing Tables
              %li
                %a{href: "page_invoice.html"} Invoice Page
              %li
                %a{href: "page_meet_our_team.html"} Meet Our Team
              %li
                %a{href: "page_coming_soon.html"} Coming Soon
              %li
                %a{href: "page_faq.html"} FAQs Page
              %li
                %a{href: "page_search.html"} Funny Boxes
              %li
                %a{href: "page_gallery.html"} Gallery Page
              %li
                %a{href: "page_registration.html"} Registration Page
              %li
                %a{href: "page_registration1.html"} Registration Option
              %li
                %a{href: "page_login.html"} Login Page
              %li
                %a{href: "page_login1.html"} Login Option
              %li
                %a{href: "page_404_error.html"} 404 Error
              %li
                %a{href: "page_404_error1.html"} 404 Error Option
              %li
                %a{href: "page_clients.html"} Clients Page
              %li
                %a{href: "page_privacy.html"} Privacy Policy
              %li
                %a{href: "page_terms.html"} Terms Of Service
              %li
                %a{href: "page_2_columns_left.html"} 2 Columns Page Left
              %li
                %a{href: "page_2_columns_right.html"} 2 Columns Page Right
              %li
                %a{href: "page_3_columns.html"} 3 Columns Page
          %li.dropdown
            %a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown", "data-toggle" => "dropdown", href: "#"}
              Features
              %i.icon-angle-down
            %ul.dropdown-menu
              %li
                %a{href: "feature_grid.html"} Grid Layout
              %li
                %a{href: "feature_boxes.html"} Content Boxes
              %li
                %a{href: "feature_typography.html"} Typography
              %li
                %a{href: "feature_tagline_boxes.html"} Tagline Boxes
              %li
                %a{href: "feature_buttons.html"} Buttons
              %li
                %a{href: "feature_icons.html"} Icons
              %li
                %a{href: "feature_thumbails.html"} Thumbails
              %li
                %a{href: "feature_components.html"} Components
              %li
                %a{href: "feature_accardion_and_tabs.html"} Accardion and Tabs
              %li
                %a{href: "feature_navigations.html"} Navigations
              %li
                %a{href: "feature_tables.html"} Tables
              %li
                %a{href: "feature_forms.html"} Forms
              %li
                %a{href: "feature_testimonials.html"} Testimonials
          %li.dropdown
            %a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown", "data-toggle" => "dropdown", href: "#"}
              Portfolio
              %i.icon-angle-down
            %ul.dropdown-menu
              %li
                %a{href: "portfolio_text_blocks.html"} Portfolio Text Blocks
              %li
                %a{href: "portfolio_2_column.html"} Portfolio 2 Columns
              %li
                %a{href: "portfolio_3_column.html"} Portfolio 3 Columns
              %li
                %a{href: "portfolio_4_column.html"} Portfolio 4 Columns
              %li
                %a{href: "portfolio_item.html"} Portfolio Item Option 1
              %li
                %a{href: "portfolio_item1.html"} Portfolio Item Option 2
          %li.dropdown
            %a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown", "data-toggle" => "dropdown", href: "#"}
              Blog
              %i.icon-angle-down
            %ul.dropdown-menu
              %li
                %a{href: "blog_page.html"} Blog Page
              %li
                %a{href: "blog_large.html"} Blog Large
              %li
                %a{href: "blog_medium.html"} Blog Medium
              %li
                %a{href: "blog_full_width.html"} Blog Full Width
              %li
                %a{href: "blog_left_sidebar.html"} Blog Left Sidebar
              %li
                %a{href: "blog_right_sidebar.html"} Blog Right Sidebar
              %li
                %a{href: "blog_item_option1.html"} Blog Item Option 1
              %li
                %a{href: "blog_item_option2.html"} Blog Item Option 2
          %li.dropdown
            %a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown", "data-toggle" => "dropdown", href: "#"}
              Contacts
              %i.icon-angle-down
            %ul.dropdown-menu
              %li
                %a{href: "page_contact1.html"} Contacts Default
              %li
                %a{href: "page_contact2.html"} Contacts Option 1
              %li
                %a{href: "page_contact3.html"} Contacts Option 2

          %li.hidden-sm
            %a.search
              %i.icon-search.search-btn
        .search-open
          .input-group
            %input.form-control{placeholder: "Search", type: "text"}/
            %span.input-group-btn
              %button.btn-u{type: "button"} Go

app/views/layouts/_slider.html.haml
/ === Slider ===
.slider-inner
  #da-slider.da-slider

    .da-slide
      %h2.slider-header
        %i Explore the world
        %br/
        %i with guided trips
      %p
        %i Reviews, information
        %br/
        %i and personal experience 
        %br
        %i about tours world wide.
      .da-img.da-content

        // main Search field
        = form_tag trips_path, :class => 'slider-searchbar tag-box tag-box-v6', :method => 'get' do
          = hidden_field_tag :location_id, '', :class => 'autosuggest-location-id'
          %h3.margin-bottom-30 Find a Trip in your prefered location
          .input-group
            = text_field_tag 'search', '', :placeholder => "Country or City", :class => 'form-control autosuggest-location'
            %span.input-group-btn
              = button_tag icon_label(t('button.search'), 'search'), :class => 'btn btn-u'
    
    .da-slide
      %h2.slider-header
        %i Plan your trip 
        %br
        %i in advance
      %p
        %i Stop checking different agencies on-site
        %br
        %i get in touch with the tour-guides online.
        %br
        %i One place for all offers
      .trips-preview.da-img.da-content
        - Trip.limit(3).each do |trip|
          .tag-box.tag-box-v6
            = render 'trips/trip_small', :trip => trip

    .da-arrows
      %span.da-arrows-prev
      %span.da-arrows-next

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GuidedTrips" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <!-- Google Map -->
    <%= javascript_include_tag 'http://maps.google.com/maps/api/js?sensor=false&amp;language=en' %>
  </head>
  <body>

  <%= render 'layouts/login_bar' %>

    <% if user_signed_in? and current_user.is_agency? %> 
        <%= render 'static/menu_logged_in_agency' %>
    <% elsif user_signed_in? %>   
        <%= render 'static/menu_logged_in' %>
    <% else %>
        <%= render 'static/menu_logged_out' %>
    <% end %>
  <%#= render 'layouts/sample_navigation' %>

    <%= show_flash_notice flash %>
 
  <%= yield %> 

  <%= render 'layouts/footer' %>

  <div id="modal_container"></div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

    <script type="text/javascript">
        jQuery(document).ready(function() {
            App.init();
            App.initSliders();
            App.initFancybox();
            Index.initParallaxSlider();
        });
    </script>
    <!--[if lt IE 9]>
        <script src="assets/plugins/respond.js"></script>
    <![endif]-->

    <%= yield :doc_footer %>

  </body>
</html>

app/views/layouts/modal.html.haml
/ Modal
.modal{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title= yield( :modal_header )
      
      .modal-body
        = yield( :modal_body )
      
      - footer = yield( :modal_footer )  
      - unless footer.blank? 
        .modal-footer
          %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close
          = footer.html_safe    